In [ ]:
import pandas as pd
import numpy as np

In [2]:
trust = pd.read_csv("../epinions/epinions/user_rating.txt",sep=r"\s+",header=None,names=["source","target","value","creation"])

In [9]:
mc = pd.read_csv("../epinions/epinions/mc.txt",sep="|",header=None,names=["content_id","author_id","subject_id"])

In [4]:
ratings = pd.read_csv("../epinions/epinions/rating.txt",sep=r"\s+",header=None,names=[ "object_id","member_id","rating","status","creation","last_modified","type","vertical_id"])

In [5]:
trust.head()

       source     target  value    creation
0  3287060356     232085     -1  2001/01/10
1  3288305540     709420      1  2001/01/10
2  3290337156     204418     -1  2001/01/10
3  3294138244     269243     -1  2001/01/10
4  3294138244  170692484     -1  2001/01/10

In [6]:
trust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 841372 entries, 0 to 841371
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   source    841372 non-null  int64
 1   target    841372 non-null  int64
 2   value     841372 non-null  int64
 3   creation  841372 non-null  object
dtypes: int64(3), object(1)
memory usage: 25.7+ MB

In [7]:
trust.describe()

             source        target          value
count  8.413720e+05  8.413720e+05  841372.000000
mean   3.839342e+09  2.771725e+09       0.705945
std    1.221076e+10  1.010336e+10       0.708267
min    1.997810e+05  1.997810e+05      -1.000000
25%    3.144350e+05  2.903310e+05       1.000000
50%    4.772070e+05  4.323175e+05       1.000000
75%    6.989030e+05  6.675410e+05       1.000000
max    8.401516e+10  8.398816e+10       1.000000

In [10]:
mc.head()

   content_id  author_id    subject_id
0     1445594     718357  1.490024e+11
1     1445595     220568  1.490036e+11
2     1445596     717325  5.303145e+09
3     1445597     360156  1.926209e+11
4     1445598     718857  1.490022e+11

In [11]:
mc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560144 entries, 0 to 1560143
Data columns (total 3 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   content_id  1560144 non-null  int64
 1   author_id   1560144 non-null  int64
 2   subject_id  1559803 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 35.7 MB

In [12]:
mc.describe()

         content_id     author_id    subject_id
count  1.560144e+06  1.560144e+06  1.559803e+06
mean   2.299295e+10  1.079286e+10  5.327210e+10
std    3.422233e+10  2.253756e+10  1.035571e+11
min    1.065180e+05  1.997750e+05  1.400000e+01
25%    1.123698e+06  3.330180e+05  8.788100e+04
50%    1.542466e+06  5.189630e+05  1.615600e+05
75%    4.160086e+10  5.883072e+09  7.023072e+09
max    1.136449e+11  8.827421e+10  5.796335e+11

In [13]:
ratings.head()

,object_id,member_id,rating,status,creation,last_modified,type,vertical_id
0,139431556,591156,5,0,2001/01/10,1,2518365,NaN
1,139431556,1312460676,5,0,2001/01/10,1,2518365,NaN
2,139431556,204358,5,0,2001/01/10,1,2518365,NaN
3,139431556,368725,5,0,2001/01/10,1,2518365,NaN
4,139431556,277629,5,0,2001/01/10,1,2518365,NaN

In [14]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13668320 entries, 0 to 13668319
Data columns (total 8 columns):
 #   Column         Dtype
---  ------         -----
 0   object_id      int64
 1   member_id      int64
 2   rating         int64
 3   status         int64
 4   creation       object
 5   last_modified  object
 6   type           int64
 7   vertical_id    float64
dtypes: float64(1), int64(5), object(2)
memory usage: 834.2+ MB

In [15]:
ratings.describe()

,object_id,member_id,rating,status,type,vertical_id
count,1.366832e+07,1.366832e+07,1.366832e+07,1.366832e+07,1.366832e+07,1.366747e+07
mean,9.114949e+09,9.881863e+08,4.673476e+00,2.975845e-02,1.357532e+02,4.495984e+09
std,1.682886e+10,3.821293e+09,6.983102e-01,1.699202e-01,1.845140e+04,2.693161e+10
min,7.194400e+05,1.997750e+05,1.000000e+00,0.000000e+00,-1.000000e+00,-2.000000e+01
25%,1.037347e+06,2.602510e+05,5.000000e+00,0.000000e+00,1.000000e+00,2.522131e+06
50%,1.487100e+06,3.480910e+05,5.000000e+00,0.000000e+00,1.000000e+00,2.522498e+06
75%,7.692062e+09,5.265230e+05,5.000000e+00,0.000000e+00,1.000000e+00,2.522545e+06
max,6.558217e+10,4.638150e+10,6.000000e+00,1.000000e+00,2.531404e+06,1.659158e+11

In [16]:
print("Trust network : " , trust.shape)
print("Content : " , mc.shape)
print("Ratings : ", ratings.shape)

Trust network :  (841372, 4)
Content :  (1560144, 3)
Ratings :  (13668320, 8)

In [17]:
#how many trust and distrust edges
trust["value"].value_counts()

value
 1    717667
-1    123705
Name: count, dtype: int64

In [19]:
#count unique users
users = pd.unique(pd.concat([trust["source"],trust["target"]]))
len(users)

131828

In [20]:
#duplicates 
trust.duplicated().sum()

np.int64(0)

In [21]:
trust.isnull().sum()

source      0
target      0
value       0
creation    0
dtype: int64

In [22]:
trust["source"].nunique()

95318

In [23]:
trust["target"].nunique()

84601

In [24]:
edges = trust.copy()

In [25]:
edges.head()

       source     target  value    creation
0  3287060356     232085     -1  2001/01/10
1  3288305540     709420      1  2001/01/10
2  3290337156     204418     -1  2001/01/10
3  3294138244     269243     -1  2001/01/10
4  3294138244  170692484     -1  2001/01/10

In [26]:
edges["relationship"] = edges["value"].map({1:"Trust",-1:"Distrust"})

In [27]:
edges.head(10)

       source     target  value    creation relationship
0  3287060356     232085     -1  2001/01/10     Distrust
1  3288305540     709420      1  2001/01/10        Trust
2  3290337156     204418     -1  2001/01/10     Distrust
3  3294138244     269243     -1  2001/01/10     Distrust
4  3294138244  170692484     -1  2001/01/10     Distrust
5  3296759684  347967364      1  2001/01/10        Trust
6   167022468     707034      1  2001/01/10        Trust
7   168267652     214139      1  2001/01/10        Trust
8   169447300     338102      1  2001/01/10        Trust
9   169447300     382733      1  2001/01/10        Trust

In [28]:
nodes = pd.DataFrame({"id":users})

In [29]:
nodes.head()

           id
0  3287060356
1  3288305540
2  3290337156
3  3294138244
4  3296759684

In [30]:
len(nodes)

131828

In [32]:
edges["value"].value_counts()

value
 1    717667
-1    123705
Name: count, dtype: int64

In [33]:
trust["value"].value_counts(normalize=True)

value
 1    0.852972
-1    0.147028
Name: proportion, dtype: float64

In [34]:
summary = pd.DataFrame({"Metric" : ["Users","Edges","Trust edges","Distrust edges"],"value":[len(nodes),len(edges),(edges["value"]==1).sum(),(edges["value"]==-1).sum()]})

In [35]:
summary

           Metric   value
0           Users  131828
1           Edges  841372
2     Trust edges  717667
3  Distrust edges  123705

In [36]:
#Create nodes.csv

nodes = pd.DataFrame({"Id":users})
nodes

                 Id
0        3287060356
1        3288305540
2        3290337156
3        3294138244
4        3296759684
...             ...
131823  83931795332
131824       574099
131825  68954984324
131826  83988156292
131827  71671189380

[131828 rows x 1 columns]

In [37]:
nodes.to_csv("nodes.csv",index=False)

In [48]:
#create edges.csv
edges = trust.copy()
edges = edges.rename(columns={"source":"Source","target":"Target"})

In [49]:
edges

             Source       Target  value    creation
0        3287060356       232085     -1  2001/01/10
1        3288305540       709420      1  2001/01/10
2        3290337156       204418     -1  2001/01/10
3        3294138244       269243     -1  2001/01/10
4        3294138244    170692484     -1  2001/01/10
...             ...          ...    ...         ...
841367       377602  75017588612      1  2003/08/12
841368  83329126276       203962      1  2003/08/12
841369  79757938564   1955106692      1  2003/08/12
841370  66846035844       399055      1  2003/08/12
841371       361404  81580625796     -1  2003/08/12

[841372 rows x 4 columns]

In [50]:
edges["Relationship"] = edges["value"].map({1:"Trust",-1:"Distrust"})

In [51]:
edges["Type"] = "Directed"

In [52]:
edges["Weight"] = 1

In [53]:
edges

,Source,Target,value,creation,Relationship,Type,Weight
0,3287060356,232085,-1,2001/01/10,Distrust,Directed,1
1,3288305540,709420,1,2001/01/10,Trust,Directed,1
2,3290337156,204418,-1,2001/01/10,Distrust,Directed,1
3,3294138244,269243,-1,2001/01/10,Distrust,Directed,1
4,3294138244,170692484,-1,2001/01/10,Distrust,Directed,1
...,...,...,...,...,...,...,...
841367,377602,75017588612,1,2003/08/12,Trust,Directed,1
841368,83329126276,203962,1,2003/08/12,Trust,Directed,1
841369,79757938564,1955106692,1,2003/08/12,Trust,Directed,1
841370,66846035844,399055,1,2003/08/12,Trust,Directed,1
841371,361404,81580625796,-1,2003/08/12,Distrust,Directed,1

In [54]:
edges = edges[["Source","Target","Type","Weight","Relationship"]]

In [55]:
edges

             Source       Target      Type  Weight Relationship
0        3287060356       232085  Directed       1     Distrust
1        3288305540       709420  Directed       1        Trust
2        3290337156       204418  Directed       1     Distrust
3        3294138244       269243  Directed       1     Distrust
4        3294138244    170692484  Directed       1     Distrust
...             ...          ...       ...     ...          ...
841367       377602  75017588612  Directed       1        Trust
841368  83329126276       203962  Directed       1        Trust
841369  79757938564   1955106692  Directed       1        Trust
841370  66846035844       399055  Directed       1        Trust
841371       361404  81580625796  Directed       1     Distrust

[841372 rows x 5 columns]

In [56]:
edges.to_csv("edges.csv",index=False)

In [58]:
#most active users

degree = pd.concat([edges["Source"],edges["Target"]]).value_counts()
degree

210284         3622
413254         2365
204418         2345
239694         2314
350170         2231
               ...
83505287044       1
196841348         1
71671189380       1
3287060356        1
223055748         1
Name: count, Length: 131828, dtype: int64

In [59]:
top_users = degree.head(5000).index

In [64]:
sample_edges = edges[
    edges["Source"].isin(top_users) &
    edges["Target"].isin(top_users)
]

In [65]:
sample_edges = sample_edges.sample(
    n=100000,
    random_state=42
)

In [66]:
sample_nodes = pd.DataFrame({
    "Id": pd.unique(
        pd.concat([
            sample_edges["Source"],
            sample_edges["Target"]
        ])
    )
})

In [67]:
sample_nodes["Label"] = sample_nodes["Id"]

sample_nodes.to_csv("sample_nodes.csv", index=False)
sample_edges.to_csv("sample_edges.csv", index=False)

In [68]:
sample_nodes

               Id        Label
0          386501       386501
1      3169947524   3169947524
2          356173       356173
3          556414       556414
4          692821       692821
...           ...          ...
4995   9853505412   9853505412
4996       567553       567553
4997       201463       201463
4998       480514       480514
4999  14792626052  14792626052

[5000 rows x 2 columns]

In [69]:
print("Nodes:", len(sample_nodes))
print("Edges:", len(sample_edges))

Nodes: 5000
Edges: 100000